[package]
name = "qoir-rs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
libc = "0.2.172"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.23"

[features]
default = ["simd"]
large_luts = []
simd = []
